title: Silmä Huone Wiki
description: A documentation center for the Noita eye puzzle community
theme: just-the-docs

url: https://loganmcbroom.github.io/loganmcbroom.github.io

aux_links:
  "Silmä Huone Wiki Repository": 
    - "https://github.com/loganmcbroom/loganmcbroom.github.io"

# External navigation links
nav_external_links:
  - title: Noita Discord
    url: https://discord.gg/noita
    hide_icon: false


# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.ico"

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# For copy button on code
enable_copy_code_button: true


