title: Silma Huone Wiki
description: A documentation center for the Noita eye puzzle community
theme: just-the-docs

url: https://loganmcbroom.github.io/loganmcbroom.github.io

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/loganmcbroom/loganmcbroom.github.io
